{
  'PATH': 'data/snacks/',
  'DATA_FILES_SETTINGS': {
    'folder': 'raw_data',
    'ext': 'gz', # data files'  extension
    #'file_name': 'parfiumeriia_2023-02-01_2023-02-28_20240106_143305.csv',
    'search_cols': [ 2,3, 4, 5, 6, 7, 8, 9 ]
  },
  'DICT_FILE_SETTINGS': {
    'folder': 'dict',
    'ext': 'csv',
    'file_name': 'merged_dictionary.csv',
    'actions': { # columns' indexes in the file_search containing settings
      'action': 0,  # update or delete setting
      'term': 3  # search string used after match setting in the SQL query
    },
    clean_cols_ids: { # indexes of columns containing output values
      'cat': 4,
      'adv': 5,
      'bra': 6,
      'sbr': 7,
      'mdl': 8,
      'cln_0': 9,
      'cln_1': 10,
      'cln_2': 11,
      'cln_3': 12,
      'cln_4': 13,
      'cln_5': 14
    }
  },
  'DATABASE_SETTINGS': {
    folder: 'data_base',
    file_name: 'db_example',
    table_name: 'data_table'
  },
  'READ_SETTINGS': { # general settings for pandas CSV reader
    'from_csv': {
      'sep': ';',
      'on_bad_lines': 'skip',
      'encoding': 'utf-8',
      'index_col': False,
      'skiprows': Null,
      'decimal': ',',
      'header': 0  # ignor column names in CSV file
    }
  },
  'EXPORT_SETTINGS': {
    'folder': 'clean_data',
    'to_csv': { # general settings for pandas CSV reader
      'chunksize': 10000,
      'sep': ';',
      'encoding': 'UTF-8',
      'mode': 'a',
      'header': True,
      'index': False,
      'compression': { 'method': 'gzip' }
    }
  }
}